site_name: DriveShop Clip Tracking System
site_url: https://aininja-pro.github.io/DriveShop_Clip/
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs: false
extra_css:
  - assets/custom.css



nav:
  - Home: README.md

  - Overview:
      - Project Overview: module_overview.md
      - Architecture: dashboard.md

  - Modules:
      - Ingest: ingest.md
      - Analysis: analysis.md
      - API Utilities: api-utils.md
      - Core Utilities: core-utils.md
      - Crawler: crawler.md
      - Crawler Utils: crawler-utils.md
      - CreatorIQ: creatoriq.md
      - Other Utilities: other-utils.md

  - Deployment & Support:
      - Setup Guide: documentation/setup.md
      - Future Enhancements: documentation/future.md
      - Support & Troubleshooting: documentation/support.md
